version: "v2.23.3-desktop.2"
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - '5023:5000'
    volumes:
      - ./api:/app

  myblog:
    build: ./myblog
    container_name: myblog_c
    ports:
      - '3013:3000'
    stdin_open: true


